### PR TITLE
UMNNs implementation

### PR DESCRIPTION
**Pull request by AWehenkel**
Hi again,

I implemented the coupling and autoregressive version of UMNNs. To do so without putting a mess in your code I added a dependency on the UMNN package (it implements Clenshaw-Curtis quadrature) and a subfolder MonotonicNormalizer. 
I also adapted your unit tests for these two new classes and tested if it was working well on the two moons notebooks. Everything seems ok but I did not check every corner cases.

Cheers,

Antoine

### CODE REVIEW

**Comment by AWehenkel** [comment]
Hi @arturbekasov! By chance did you get time to check my PR? :) 
Thanks in advance!

**Comment by arturbekasov** [comment]
Hi @AWehenkel. Really sorry for the wait — been low on spare brain cycles lately. I’ll find some this week to take a look at the PR. Thanks again for taking the time to get this in! Cheers, Artur

**Comment by arturbekasov** [comment]
LGTM, thanks! There are some minor stylistic discrepancies with the rest of the code, but I'll clean those up myself in a separate commit. Sorry again for the delay.

**Comment by AWehenkel** [comment]
Thanks! :)

**Pull request merged**
