### PR TITLE
Allow identity initialization for rational quadratic spline transform

### PR DESCRIPTION
**Pull request by invemichele**
This PR implements what suggested in #50, adding a flag to ensure backward compatibility.
I have been using it for quite some time now and I think it might be useful for someone else as well

### CODE REVIEW

**Comment by invemichele** [comment]
Our paper that uses this code has been accepted and will soon be published. It would be great if this PR could be merged, so that it would be easier for anyone to reproduce our results.

@arturbekasov is there anything you want me to add/change before merging?

**Comment by arturbekasov** [comment]
Sorry for the delay, @invemichele -- thanks a lot for taking the time to implement this.

LGTM in general, a nitpick: can we rename the parameter `allow_identity_init` to `enable_identity_init`?

**Comment by invemichele** [comment]
sure, no problem!

**Comment by arturbekasov** [comment]
Thank you very much, @invemichele!

**Pull request merged**
